{
 "title": "tcp-pinger",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "avg open TCP connection time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(tcp-pinger.*.*.avg-pings-time, 2)"
    }
   ]
  },
  {
   "title": "max open TCP connection time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(tcp-pinger.*.*.max-pings-time, 2)"
    }
   ]
  },
  {
   "title": "open TCP connection errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(tcp-pinger.*.*.errors, 2)"
    }
   ]
  },
  {
   "title": "open TCP connection count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(tcp-pinger.*.*.ping-count, 2)"
    }
   ]
  }
 ]
}